import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "./contexts/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ApolloWrapper>
        <body className={`${inter.className} p-4`}>

          <header className="py-4 border-b-2 border-emerald-300">

            <h1 className="text-2xl font-extrabold">LogsApp</h1>

          </header>

          {children}
        </body>
      </ApolloWrapper>
    </html>
  );
}
