import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "./contexts/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ApolloWrapper>
        <body className={`${inter.className} h-full min-h-screen bg-gradient-to-br from-black to-zinc-900/80 p-4 flex flex-col gap-4 transition-all`}>

          <header className="py-2 border-b-2 border-emerald-500">

            <h1 className="text-2xl font-bold">LogsApp</h1>

          </header>

          {children}
        </body>
      </ApolloWrapper>
    </html>
  );
}
